export const REQUEST_MAIN_WEATHER_DATA = 'REQUEST_MAIN_WEATHER_DATA'
export const REQUEST_SUCCESS_MAIN_WEATHER_DATA = 'REQUEST_SUCCES_MAIN_WEATHER_DATA'
export const REQUEST_FAILURE_MAIN_WEATHER_DATA = 'REQUEST_FAILURE_MAIN_WEATHER_DATA'
